name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main branch(change according to your branch)
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload entire repository
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}  # Pass your GitHub token as environment variable
          FORMSPREE_ID: ${{ secrets.FORMSPREE_ID }}  # Pass your Formspree ID as environment variable
